# Generated by Django 4.1.7 on 2023-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='livematch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname1', models.CharField(max_length=40)),
                ('teamname2', models.CharField(max_length=40)),
                ('socre1', models.IntegerField(default=0)),
                ('socre2', models.IntegerField(default=0)),
                ('wicket1', models.IntegerField(default=0)),
                ('wicket2', models.IntegerField(default=0)),
                ('over1', models.IntegerField(default=20)),
                ('over2', models.IntegerField(default=20)),
                ('balls', models.IntegerField(default=120)),
            ],
        ),
    ]
