# Generated by Django 4.1.7 on 2023-03-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_livematch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livematch',
            old_name='socre1',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='livematch',
            old_name='socre2',
            new_name='score2',
        ),
    ]
