# Generated by Django 4.1.7 on 2023-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_livematch_current_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='over1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livematch',
            name='over2',
            field=models.IntegerField(default=0),
        ),
    ]
