# Generated by Django 4.1.7 on 2023-03-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_alter_livematch_over1_alter_livematch_over2'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.IntegerField(default=20)),
                ('venue', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.livematch')),
            ],
        ),
    ]
