# Generated by Django 4.1.7 on 2023-03-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0008_match_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='over1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='livematch',
            name='over2',
            field=models.FloatField(default=0),
        ),
    ]
