# Generated by Django 4.1.7 on 2023-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0009_alter_livematch_over1_alter_livematch_over2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wicket',
            field=models.IntegerField(default=0),
        ),
    ]
