# Generated by Django 4.1.7 on 2023-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0010_player_score_player_wicket'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='brun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='overs',
            field=models.FloatField(default=0),
        ),
    ]
